# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DistrictID', models.IntegerField()),
                ('District', models.CharField(blank=True, default='', max_length=255)),
                ('AcademicYear', models.IntegerField()),
                ('Subject', models.CharField(blank=True, default='', max_length=255)),
                ('Subgroup', models.CharField(blank=True, default='', max_length=255)),
                ('GradeLevel', models.CharField(blank=True, default='', max_length=255)),
                ('ParticipationRate2014to2015', models.FloatField()),
                ('PercentageMeetsORExceeds2014to2015', models.FloatField()),
            ],
            options={
                'ordering': ('School',),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolID', models.IntegerField()),
                ('School', models.CharField(max_length=65)),
                ('District', models.CharField(max_length=65)),
                ('DistID', models.IntegerField()),
            ],
            options={
                'ordering': ('School',),
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
