# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='SchoolID',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='performance',
            name='District',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='performance',
            name='GradeLevel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='performance',
            name='ParticipationRate2014to2015',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='PercentageMeetsORExceeds2014to2015',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='Subgroup',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='performance',
            name='Subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
